### ISSUE TITLE
New SSG Feature for palpatine: Support --config with JSON file

### ISSUE THREAD

**Issue by saminarp** [batunpc/palpatine#11]
Hi, 

I would like to add a new feature to Palpatine SSG. Through this new feature, it would be able to support the Config file with the 
--config flag. 

Here is the list of all that I will implement as specified in the lab 4 instructions. 

1. The -c or --config flags accept a file path to a JSON config file.
2. If the file is missing, or can't be parsed as JSON, exit with an appropriate error message.
3. If the -c or --config option is provided, ignore all other options (i.e., a config file overrides other options on the command line).
4. The program should ignore any options in the config file it doesn't recognize.
5. If the config file misses any options, assume the usual defaults. For example, use dist/ as the output directory if it isn't specified.

:) I will be reaching out through Slack with questions if any!

**Comment by saminarp** [comment]
Hello, 

As lab4 requires us to provide config file which is in json format, I need to use the following library [nlohmann/json](https://github.com/nlohmann/json). Could you help me insert this library like the way you did for argaprser and termcolor? Thanks!

**Comment by batunpc** [comment]
Hi! please see https://github.com/batunpc/palpatine/pull/12

**Comment by batunpc** [comment]
Closes: https://github.com/batunpc/palpatine/pull/12
