### ISSUE TITLE
Enhance modularity by moving the argparse and termcolor in src directory

### ISSUE THREAD

**Issue by saminarp** [batunpc/palpatine#4]
In the app/main.cpp, the argparse dependency and termcolor is making the main.cpp look cluttered. It is best practice to have only the main function in main.cpp. We can move the argparse and termcolor in src directory to make it more modular.

**Comment by batunpc** [comment]
The external libraries I used `argparse` and `termcolor` are header only files and when I try to link it into libraries I have instead of the Executable it does not see the libray. I am not certain on how to link a library into another.
