### ISSUE TITLE
Provide more documentation on CMake configurations 

### ISSUE THREAD

**Issue by saminarp** [batunpc/palpatine#5]
Provide more explanations about CMake configurations. For example, what does the config folder actually do? And how does CMake help you to configure external dependencies? This could make your README more powerful and help users a lot!

**Comment by batunpc** [comment]
Thank you for the review! config directory is responsible with the versioning of the project. Instead of manually typing we can retrieve the version from config.hpp file. It's a nice feature by CMake. I will update the readme accordingly! 👍

**Comment by batunpc** [comment]
I have added concise but descriptive explanation on how I have handled this in the end of my readme. Let me know if it looks enough. I am thinking to write more details in the blog regarding documentation

**Comment by saminarp** [comment]
Great. Looks good.
