### ISSUE TITLE
Markdown support lab 2 

### ISSUE THREAD

**Issue by saminarp** [batunpc/palpatine#6]
Hi, I am looking at your code and have started adding markdown support for 'link'. I will be sending a pull request soon.

Happy collaborating!

**Comment by batunpc** [comment]
Sounds great, same comments for yours

**Comment by saminarp** [comment]
So, here is what I am going to do. The .txt file processing you have on your code will work exactly as they are. However, when the input file is .md, I am going to write some code to work accordingly. I am thinking to add the markdown feature for the link. I might ask you subsequent questions if I run into issues. Let me know if it sounds good to you.

**Comment by batunpc** [comment]
Sounds good! Let me know how it goes for you and reopen this issue if any questions arises or you can reach me from Slack as usual
